# Docker
- task: Docker@2
  inputs:
    containerRegistry: 'geralexgr-docker-repo'
    repository: 'aksjavarepo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

- task: Docker@2
  inputs:
    containerRegistry: 'geralexgr-docker-repo'
    repository: 'geralexgr/aksjavarepo'
    command: 'build'
    Dockerfile: '**/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
